---
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app

  db:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=faucet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"

volumes:
  postgres_data: