# Generated by Django 5.0.1 on 2025-02-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=42)),
                ("transaction_hash", models.CharField(max_length=66)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["wallet_address"], name="api_transac_wallet__8da284_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="api_transac_created_752f02_idx"
                    ),
                ],
            },
        ),
    ]
