# Generated by Django 5.0.1 on 2025-02-07 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="api_transac_created_752f02_idx",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=8, max_digits=18, verbose_name="Amount of ETH being sent"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("SUCCESS", "Success"), ("FAILED", "Failed")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_hash",
            field=models.CharField(
                max_length=66,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^0x([A-Fa-f0-9]{64})$")
                ],
                verbose_name="Ethereum Transaction hash",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet_address",
            field=models.CharField(
                max_length=42,
                validators=[
                    django.core.validators.RegexValidator(regex="^0x[a-fA-F0-9]{40}$")
                ],
                verbose_name="Ethereum Wallet Address",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_hash"], name="api_transac_transac_50adc1_idx"
            ),
        ),
    ]
